// The MTN Mobile Money Open API, as thin a wrapper as the API allows.
//
// Two products, two subscription keys, two token endpoints, one shape:
//   Collections  — pull money from a customer  (/collection/...)
//   Disbursements — push money to a driver     (/disbursement/...)
//
// Every call needs three headers beyond the token: the product's own
// subscription key, a target environment string MTN gives you per market
// ("sandbox", or something like "mtnrwanda" in production), and an
// X-Reference-Id which is OUR uuid for the transaction. That reference is
// the only handle for asking about it later, so it is generated by the
// caller and stored before the request goes out.
import crypto from 'crypto';

const BASE_URL = process.env.MOMO_BASE_URL || 'https://sandbox.momodeveloper.mtn.com';
const TARGET_ENV = process.env.MOMO_TARGET_ENVIRONMENT || 'sandbox';
// Sandbox only settles in EUR. Production uses the market's own currency,
// which for Rwanda is RWF and has no minor unit — 15000 means fifteen
// thousand francs, not a hundred and fifty.
const CURRENCY = process.env.MOMO_CURRENCY || 'EUR';
const CALLBACK_BASE = process.env.MOMO_CALLBACK_BASE_URL || '';
const REQUEST_TIMEOUT_MS = 15_000;

const PRODUCTS = {
    collection: {
        path: 'collection',
        subscriptionKey: () => process.env.MOMO_COLLECTION_SUBSCRIPTION_KEY,
        apiUser: () => process.env.MOMO_COLLECTION_API_USER,
        apiKey: () => process.env.MOMO_COLLECTION_API_KEY,
    },
    disbursement: {
        path: 'disbursement',
        subscriptionKey: () => process.env.MOMO_DISBURSEMENT_SUBSCRIPTION_KEY,
        apiUser: () => process.env.MOMO_DISBURSEMENT_API_USER,
        apiKey: () => process.env.MOMO_DISBURSEMENT_API_KEY,
    },
};

export class MomoError extends Error {
    constructor(message, { status = null, code = null, retryable = false } = {}) {
        super(message);
        this.name = 'MomoError';
        this.status = status;
        this.code = code;
        // Distinguishes "MTN said no" from "we could not reach MTN". The
        // first is an answer and must not be retried; the second is silence
        // and must be.
        this.retryable = retryable;
    }
}

export function isMomoConfigured(product = 'collection') {
    const p = PRODUCTS[product];
    return Boolean(p?.subscriptionKey() && p.apiUser() && p.apiKey());
}

// Tokens last an hour. Cached per product and refreshed a minute early, so a
// token does not expire between being read and being used.
const tokenCache = new Map();

async function accessToken(product) {
    const cached = tokenCache.get(product);
    if (cached && cached.expiresAt > Date.now() + 60_000) return cached.token;

    const p = PRODUCTS[product];
    if (!isMomoConfigured(product)) {
        throw new MomoError(`MoMo ${product} is not configured on this server.`, { code: 'NOT_CONFIGURED' });
    }

    const basic = Buffer.from(`${p.apiUser()}:${p.apiKey()}`).toString('base64');
    const response = await fetchWithTimeout(`${BASE_URL}/${p.path}/token/`, {
        method: 'POST',
        headers: {
            Authorization: `Basic ${basic}`,
            'Ocp-Apim-Subscription-Key': p.subscriptionKey(),
            'Content-Length': '0',
        },
    });

    if (!response.ok) {
        throw new MomoError(`Could not get a MoMo ${product} token (${response.status}).`, {
            status: response.status,
            // A 401 here is bad credentials and will fail identically for
            // ever; anything else may be transient.
            retryable: response.status !== 401,
        });
    }

    const body = await response.json();
    tokenCache.set(product, {
        token: body.access_token,
        expiresAt: Date.now() + Number(body.expires_in || 3600) * 1000,
    });
    return body.access_token;
}

async function fetchWithTimeout(url, options) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
    try {
        return await fetch(url, { ...options, signal: controller.signal });
    } catch (error) {
        throw new MomoError(`MoMo request failed: ${error.message}`, { code: 'UNREACHABLE', retryable: true });
    } finally {
        clearTimeout(timer);
    }
}

async function call(product, { method, path, reference, body }) {
    const p = PRODUCTS[product];
    const token = await accessToken(product);
    const headers = {
        Authorization: `Bearer ${token}`,
        'X-Target-Environment': TARGET_ENV,
        'Ocp-Apim-Subscription-Key': p.subscriptionKey(),
    };
    if (reference) headers['X-Reference-Id'] = reference;
    if (body) headers['Content-Type'] = 'application/json';
    // Per-transaction callback URL. The reference is in the path because
    // MTN's callback body cannot be relied on to identify the transaction,
    // and matching on the URL is unambiguous.
    if (body && CALLBACK_BASE && reference) {
        headers['X-Callback-Url'] = `${CALLBACK_BASE.replace(/\/$/, '')}/${reference}`;
    }

    const response = await fetchWithTimeout(`${BASE_URL}/${p.path}/${path}`, {
        method,
        headers,
        body: body ? JSON.stringify(body) : undefined,
    });
    return response;
}

export function newReference() {
    return crypto.randomUUID();
}

/**
 * Ask a customer to pay. Returns once MTN has accepted the request, which is
 * long before the customer has done anything — 202 means "we will push a PIN
 * prompt to that handset", not "they paid".
 */
export async function requestToPay({ reference, msisdn, amount, externalId, payerMessage, payeeNote }) {
    const response = await call('collection', {
        method: 'POST',
        path: 'v1_0/requesttopay',
        reference,
        body: {
            // A string, and MTN is strict about it. For RWF there is no
            // decimal part to send.
            amount: String(amount),
            currency: CURRENCY,
            externalId: String(externalId),
            // MSISDN without the leading +, which is the one formatting
            // detail MTN rejects silently-looking requests over.
            payer: { partyIdType: 'MSISDN', partyId: msisdn.replace(/^\+/, '') },
            payerMessage: payerMessage.slice(0, 160),
            payeeNote: payeeNote.slice(0, 160),
        },
    });

    if (response.status === 202) return { accepted: true, reference };

    const detail = await response.text().catch(() => '');
    throw new MomoError(`MoMo refused the payment request (${response.status}). ${detail}`.trim(), {
        status: response.status,
        retryable: response.status >= 500,
    });
}

/**
 * The authoritative answer, and the reason the webhook is never trusted on
 * its own: MTN does not sign its callbacks, so anything that arrives at the
 * callback URL is a hint to go and ask, not a fact.
 */
export async function getRequestToPayStatus(reference) {
    const response = await call('collection', { method: 'GET', path: `v1_0/requesttopay/${reference}` });
    if (!response.ok) {
        throw new MomoError(`Could not read payment status (${response.status}).`, {
            status: response.status,
            retryable: response.status >= 500 || response.status === 404,
        });
    }
    const body = await response.json();
    return {
        status: body.status,
        financialTransactionId: body.financialTransactionId || null,
        reason: body.reason || null,
        amount: body.amount,
        currency: body.currency,
    };
}

/** Push money to a driver. Same shape as collection, opposite direction. */
export async function transfer({ reference, msisdn, amount, externalId, payeeNote }) {
    const response = await call('disbursement', {
        method: 'POST',
        path: 'v1_0/transfer',
        reference,
        body: {
            amount: String(amount),
            currency: CURRENCY,
            externalId: String(externalId),
            payee: { partyIdType: 'MSISDN', partyId: msisdn.replace(/^\+/, '') },
            payerMessage: 'Inzira driver earnings',
            payeeNote: payeeNote.slice(0, 160),
        },
    });

    if (response.status === 202) return { accepted: true, reference };

    const detail = await response.text().catch(() => '');
    throw new MomoError(`MoMo refused the transfer (${response.status}). ${detail}`.trim(), {
        status: response.status,
        retryable: response.status >= 500,
    });
}

export async function getTransferStatus(reference) {
    const response = await call('disbursement', { method: 'GET', path: `v1_0/transfer/${reference}` });
    if (!response.ok) {
        throw new MomoError(`Could not read transfer status (${response.status}).`, {
            status: response.status,
            retryable: response.status >= 500 || response.status === 404,
        });
    }
    const body = await response.json();
    return {
        status: body.status,
        financialTransactionId: body.financialTransactionId || null,
        reason: body.reason || null,
    };
}

export const MOMO_CURRENCY = CURRENCY;
